# placeholder Makefile added by PR; real one will be generated by Codex v12
.PHONY: check write strict clean
check:
	@echo 'Run: make write after generating tools/repo_healer_awk.sh'
write:
	@echo 'Generate v12 artifacts using the prompt in tools/README_repo_healer_prompts.md'
strict:
	@echo 'Strict mode placeholder'
clean:
	rm -rf build
