# placeholder; real targets generated by v12 if you choose that route
.PHONY: check write strict clean
check:
	@echo 'Generate a healer first (v11/v12/v13/v14). Then re-run.'
write:
	@echo 'Generate a healer first.'
strict:
	@echo 'Generate a healer first.'
clean:
	rm -rf build
